version: "3.8"
services:
  pgvector:
    image: pgvector/pgvector:pg16
    hostname: "pgvector"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "project_development"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    volumes:
      - project_pg_data:/var/lib/postgresql/data

volumes:
  project_pg_data:
    name: project_pg_data
